version: "3.1"

networks:
    personal:
        driver: bridge
        # external:
        #  name: srv_personal

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        env_file:
            - .env
        networks:
            - personal
        volumes:
            - ./data:/var/lib/mysql

    app:
        build: .
        restart: always
        volumes:
            - ./dist:/app/dist
            - ./assets:/app/assets
        depends_on:
            - db
        links:
            - db
        networks:
            - personal
        ports:
            - 3000:3000
        environment:
            - LETSENCRYPT_HOST=randomizer.karel-kroeze.nl
            - LETSENCRYPT_EMAIL=karel.kroeze@gmail.com
            # - VIRTUAL_HOST=randomizer.karel-kroeze.nl
            # - VIRTUAL_PORT=3000
        env_file:
            - .env
